apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: ui
spec:
  host: ui.thegym.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: 0.0.1
  - name: v2
    labels:
      version: 0.0.%BUILD_NUMBER%
